language: ruby
rvm:
        - 2.1.2
notifications:
        email: false
script: CODECLIMATE_REPO_TOKEN=8d43ae3a928f18aabb5a98065fd25344195b0bd414f8136f3a714b469291ac8a xvfb-run rspec
env:
        global:
                - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
                - JRUBY_OPTS=-Xcext.enabled=true
sudo: false

cache: bundler

addons:
        apt:
                sources: 
                        - ubuntu-sdk-team
                packages:               
                        - libqt5webkit5-dev 
                        - qtdeclarative5-dev 
                        - qtlocation5-dev 
                        - qtsensors5-dev 
                        - libgstreamer0.10-dev 
                        - libgstreamer-plugins-base0.10-dev 
                        - qt4-default

before_install: 
        #- sudo locale-gen --no-archive es_CO.UTF-8
        - psql -c 'CREATE DATABASE sal7711des_pru;' -U postgres
        - bundle install
        - cp db/structure.sql db/structure.sql.conlock
        - sed -e "s/SET lock_timeout = 0;//g" db/structure.sql.conlock >db/structure.sql
        - cp config/database.travis.yml config/database.yml
        - rake db:setup
        - rake sal7711:indices

